//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

//SCRIPT NAO UTILIZADO.
//MOTIVO: NAO CRIADO CORRETAMENTE.
using System;
namespace AssemblyCSharp
{
		public class RotateSwitch
		{
				public RotateSwitch ()
				{
				}
		}
}

